default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: songs_development
  username: <%= ENV['SONGS_DEVELOPMENT_DB_USERNAME'] %>
  password: <%= ENV['SONGS_DEVELOPMENT_DB_PASSWORD'] %>
  host: <%= ENV['SONGS_DEVELOPMENT_DB_HOST'] %>
  port: 5432

test:
  <<: *default
  database: songs_test
  username: <%= ENV['SONGS_TEST_DB_USERNAME'] %>
  password: <%= ENV['SONGS_TEST_DB_PASSWORD'] %>
  host: <%= ENV['SONGS_TEST_DB_HOST'] %>
  port: 5432

staging:
  <<: *default
  database: songs_staging
  username: <%= ENV['SONGS_DATABASE_USERNAME'] %>
  password: <%= ENV['SONGS_DATABASE_PASSWORD'] %>
  host: <%= ENV['SONGS_DATABASE_HOST'] %>
  port: 5432

production:
  <<: *default
  database: songs_production
  username: <%= ENV['SONGS_DATABASE_USERNAME'] %>
  password: <%= ENV['SONGS_DATABASE_PASSWORD'] %>
  host: <%= ENV['SONGS_DATABASE_HOST'] %>
  port: 5432
