# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9f1b0deed4293204f6648253623847fcd575606b518bedd498e7314344ef9a2d7ccacf58c9d9578b6779a8b24a90608ec4cdb7df8cbf93be39a885bfc74b3ed8

test:
  secret_key_base: 6f94c6fe40bfc8798bfbc70436f172ef8b6c06f16b1687d6feeef8e82eb1528fcd3c5d90ca918b337ca7a641039563487c5f13e97b6ff9d5de30c1fc7e1976b6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
